# Generated by Django 4.2.7 on 2024-02-08 05:19

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.image_directory_path),
        ),
    ]
