# Generated by Django 4.2.7 on 2024-02-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chat_task_id_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='task_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
