# Generated by Django 4.2.7 on 2024-03-31 13:50

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chat_task_revoked'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_vision_upload',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.vision_image_directory_path),
        ),
    ]
