# Generated by Django 4.2.7 on 2024-03-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_chat_system_messages_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='model',
            field=models.CharField(default='claude-3-opus-20240229', max_length=255),
        ),
    ]
