# Generated by Django 4.2.7 on 2024-04-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_chat_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='model',
            field=models.CharField(default='gpt-4', max_length=255),
        ),
    ]
