# Generated by Django 4.2.7 on 2024-04-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_chat_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='temperature',
            field=models.FloatField(default=0.65),
        ),
        migrations.AlterField(
            model_name='chat',
            name='top_p',
            field=models.FloatField(default=0.7),
        ),
    ]
