# Generated by Django 4.2.7 on 2024-04-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_chat_system_messages_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='model',
            field=models.CharField(default='claude-3-opus-20240229', max_length=255),
        ),
    ]
